// FIFA TLA (3-letter) → ISO 3166-1 alpha-2 for flagcdn.com
export const TLA_TO_ISO: Record<string, string> = {
  ARG: 'ar', BRA: 'br', URU: 'uy', CHI: 'cl', COL: 'co', ECU: 'ec', PER: 'pe',
  VEN: 've', PAR: 'py', BOL: 'bo',
  MEX: 'mx', USA: 'us', CAN: 'ca', CRC: 'cr', PAN: 'pa', HON: 'hn',
  SLV: 'sv', GUA: 'gt', JAM: 'jm', HAI: 'ht', TRI: 'tt', CUB: 'cu',
  FRA: 'fr', ESP: 'es', GER: 'de', POR: 'pt', ITA: 'it', NED: 'nl',
  BEL: 'be', SUI: 'ch', AUT: 'at', POL: 'pl', CZE: 'cz', HUN: 'hu',
  ROU: 'ro', SRB: 'rs', CRO: 'hr', SVK: 'sk', SVN: 'si', DEN: 'dk',
  SWE: 'se', NOR: 'no', FIN: 'fi', ISL: 'is', SCO: 'gb-sct', WAL: 'gb-wls',
  ENG: 'gb-eng', NIR: 'gb-nir', IRL: 'ie', TUR: 'tr', GRE: 'gr',
  UKR: 'ua', BUL: 'bg', ALB: 'al', MNE: 'me', MKD: 'mk', BIH: 'ba',
  GEO: 'ge', ARM: 'am', AZE: 'az', KOS: 'xk', LTU: 'lt', LAT: 'lv', EST: 'ee',
  MAR: 'ma', EGY: 'eg', TUN: 'tn', ALG: 'dz', SEN: 'sn', NGA: 'ng',
  GHA: 'gh', CMR: 'cm', CIV: 'ci', MLI: 'ml', BFA: 'bf', GUI: 'gn',
  COD: 'cd', RSA: 'za', ZIM: 'zw', UGA: 'ug', TAN: 'tz', MOZ: 'mz',
  ZAM: 'zm', ANG: 'ao', CPV: 'cv', GAB: 'ga', BEN: 'bj', TOG: 'tg',
  NAM: 'na', BOT: 'bw', LBR: 'lr', ETH: 'et',
  JPN: 'jp', KOR: 'kr', AUS: 'au', IRN: 'ir', SAU: 'sa', QAT: 'qa',
  UAE: 'ae', IRQ: 'iq', JOR: 'jo', OMN: 'om', BHR: 'bh', KWT: 'kw',
  CHN: 'cn', IDN: 'id', THA: 'th', VIE: 'vn', PHI: 'ph', MAS: 'my',
  NZL: 'nz', FIJ: 'fj', IND: 'in', PAK: 'pk',
  CUW: 'cw', UZB: 'uz',
  // Alternative codes (football-data.org / FIFA alternates / ISO-3)
  KSA: 'sa', TTO: 'tt', CUR: 'cw', HOL: 'nl', URY: 'uy',
  RSC: 'cg', SKN: 'kn',
}

// Fallback: team name (Spanish or English, lowercased) → ISO alpha-2.
// Used when home_team_code stores the full team name instead of a TLA.
const NAME_TO_ISO: Record<string, string> = {
  // Spanish names
  'uruguay': 'uy',
  'argentina': 'ar',
  'brasil': 'br',
  'colombia': 'co',
  'ecuador': 'ec',
  'venezuela': 've',
  'paraguay': 'py',
  'chile': 'cl',
  'perú': 'pe',
  'peru': 'pe',
  'bolivia': 'bo',
  'méxico': 'mx',
  'mexico': 'mx',
  'estados unidos': 'us',
  'canadá': 'ca',
  'canada': 'ca',
  'costa rica': 'cr',
  'panamá': 'pa',
  'panama': 'pa',
  'honduras': 'hn',
  'jamaica': 'jm',
  'haití': 'ht',
  'haiti': 'ht',
  'trinidad y tobago': 'tt',
  'curazao': 'cw',
  'cuba': 'cu',
  'guatemala': 'gt',
  'el salvador': 'sv',
  'francia': 'fr',
  'españa': 'es',
  'espana': 'es',
  'alemania': 'de',
  'portugal': 'pt',
  'italia': 'it',
  'países bajos': 'nl',
  'paises bajos': 'nl',
  'holanda': 'nl',
  'bélgica': 'be',
  'belgica': 'be',
  'suiza': 'ch',
  'austria': 'at',
  'polonia': 'pl',
  'república checa': 'cz',
  'republica checa': 'cz',
  'hungría': 'hu',
  'hungria': 'hu',
  'rumania': 'ro',
  'rumanía': 'ro',
  'serbia': 'rs',
  'croacia': 'hr',
  'eslovaquia': 'sk',
  'eslovenia': 'si',
  'dinamarca': 'dk',
  'suecia': 'se',
  'noruega': 'no',
  'finlandia': 'fi',
  'islandia': 'is',
  'escocia': 'gb-sct',
  'gales': 'gb-wls',
  'inglaterra': 'gb-eng',
  'irlanda del norte': 'gb-nir',
  'irlanda': 'ie',
  'turquía': 'tr',
  'turquia': 'tr',
  'grecia': 'gr',
  'ucrania': 'ua',
  'bulgaria': 'bg',
  'albania': 'al',
  'montenegro': 'me',
  'macedonia del norte': 'mk',
  'bosnia y herzegovina': 'ba',
  'georgia': 'ge',
  'armenia': 'am',
  'azerbaiyán': 'az',
  'azerbaiyan': 'az',
  'kosovo': 'xk',
  'lituania': 'lt',
  'letonia': 'lv',
  'estonia': 'ee',
  'marruecos': 'ma',
  'egipto': 'eg',
  'túnez': 'tn',
  'tunez': 'tn',
  'argelia': 'dz',
  'senegal': 'sn',
  'nigeria': 'ng',
  'ghana': 'gh',
  'camerún': 'cm',
  'camerun': 'cm',
  'costa de marfil': 'ci',
  'mali': 'ml',
  'malí': 'ml',
  'burkina faso': 'bf',
  'guinea': 'gn',
  'sudáfrica': 'za',
  'sudafrica': 'za',
  'japón': 'jp',
  'japon': 'jp',
  'corea del sur': 'kr',
  'australia': 'au',
  'irán': 'ir',
  'iran': 'ir',
  'arabia saudita': 'sa',
  'catar': 'qa',
  'emiratos árabes unidos': 'ae',
  'irak': 'iq',
  'jordania': 'jo',
  'uzbekistán': 'uz',
  'uzbekistan': 'uz',
  'nueva zelanda': 'nz',
  'vietnam': 'vn',
  'cabo verde': 'cv',
  // English-only names (football-data.org — only those not already listed above)
  'brazil': 'br',
  'united states': 'us',
  'usa': 'us',
  'trinidad and tobago': 'tt',
  'curacao': 'cw',
  'france': 'fr',
  'spain': 'es',
  'germany': 'de',
  'netherlands': 'nl',
  'belgium': 'be',
  'switzerland': 'ch',
  'croatia': 'hr',
  'czech republic': 'cz',
  'czechia': 'cz',
  'denmark': 'dk',
  'sweden': 'se',
  'norway': 'no',
  'scotland': 'gb-sct',
  'wales': 'gb-wls',
  'england': 'gb-eng',
  'turkey': 'tr',
  'ukraine': 'ua',
  'morocco': 'ma',
  "cote d'ivoire": 'ci',
  'ivory coast': 'ci',
  'cameroon': 'cm',
  'south africa': 'za',
  'japan': 'jp',
  'south korea': 'kr',
  'saudi arabia': 'sa',
  'qatar': 'qa',
  'new zealand': 'nz',
  'cape verde': 'cv',
}

export function getFlagUrl(tla: string | null | undefined): string | null {
  if (!tla) return null
  const upper = tla.toUpperCase()

  // 1. TLA / alternate-code lookup (e.g. "URU", "KSA", "TTO")
  const isoFromTla = TLA_TO_ISO[upper]
  if (isoFromTla) return `https://flagcdn.com/w160/${isoFromTla}.png`

  // 2. Direct 2-letter ISO passthrough (e.g. "uy", "sa", "cw" stored directly in DB)
  if (upper.length === 2) return `https://flagcdn.com/w160/${upper.toLowerCase()}.png`

  // 3. Full team name fallback (Spanish or English), case-insensitive + accent-stripped
  const normalized = tla
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .trim()
  const isoFromName = NAME_TO_ISO[normalized] ?? NAME_TO_ISO[tla.toLowerCase().trim()]
  if (isoFromName) return `https://flagcdn.com/w160/${isoFromName}.png`

  return null
}
