export const MUNDIAL_TEAMS = [
  // UEFA (16)
  { name: 'Alemania',              tla: 'GER' },
  { name: 'Austria',               tla: 'AUT' },
  { name: 'Bélgica',               tla: 'BEL' },
  { name: 'Bosnia y Herzegovina',  tla: 'BIH' },
  { name: 'Croacia',               tla: 'CRO' },
  { name: 'Escocia',               tla: 'SCO' },
  { name: 'España',                tla: 'ESP' },
  { name: 'Francia',               tla: 'FRA' },
  { name: 'Inglaterra',            tla: 'ENG' },
  { name: 'Noruega',               tla: 'NOR' },
  { name: 'Países Bajos',          tla: 'NED' },
  { name: 'Polonia',               tla: 'POL' },
  { name: 'Portugal',              tla: 'POR' },
  { name: 'República Checa',       tla: 'CZE' },
  { name: 'Serbia',                tla: 'SRB' },
  { name: 'Suiza',                 tla: 'SUI' },
  // CONMEBOL (7)
  { name: 'Argentina',             tla: 'ARG' },
  { name: 'Brasil',                tla: 'BRA' },
  { name: 'Colombia',              tla: 'COL' },
  { name: 'Ecuador',               tla: 'ECU' },
  { name: 'Paraguay',              tla: 'PAR' },
  { name: 'Uruguay',               tla: 'URU' },
  { name: 'Venezuela',             tla: 'VEN' },
  // CONCACAF (5)
  { name: 'Canadá',                tla: 'CAN' },
  { name: 'Curazao',               tla: 'CUW' },
  { name: 'Estados Unidos',        tla: 'USA' },
  { name: 'Honduras',              tla: 'HON' },
  { name: 'México',                tla: 'MEX' },
  // CAF (9)
  { name: 'Argelia',               tla: 'ALG' },
  { name: 'Costa de Marfil',       tla: 'CIV' },
  { name: 'Egipto',                tla: 'EGY' },
  { name: 'Ghana',                 tla: 'GHA' },
  { name: 'Marruecos',             tla: 'MAR' },
  { name: 'Nigeria',               tla: 'NGA' },
  { name: 'Senegal',               tla: 'SEN' },
  { name: 'Sudáfrica',             tla: 'RSA' },
  { name: 'Túnez',                 tla: 'TUN' },
  // AFC (9)
  { name: 'Arabia Saudita',        tla: 'SAU' },
  { name: 'Australia',             tla: 'AUS' },
  { name: 'Catar',                 tla: 'QAT' },
  { name: 'Corea del Sur',         tla: 'KOR' },
  { name: 'Irán',                  tla: 'IRN' },
  { name: 'Japón',                 tla: 'JPN' },
  { name: 'Jordania',              tla: 'JOR' },
  { name: 'Uzbekistán',            tla: 'UZB' },
  { name: 'Vietnam',               tla: 'VIE' },
  // OFC (1)
  { name: 'Nueva Zelanda',         tla: 'NZL' },
  // CAF play-off (1)
  { name: 'Cabo Verde',            tla: 'CPV' },
]
