export type Striker = { name: string; country: string; code: string; photo?: string | null }

export const PLAYER_COLORS: Record<string, string> = {
  uy: '#5AAAD4',
  de: '#1a1a1a',
  es: '#AA151B',
  py: '#CC0000',
  ar: '#74ACDF',
  gh: '#006B3F',
  br: '#009C3B',
  pt: '#006600',
  jp: '#BC002D',
  mx: '#006847',
  'gb-eng': '#CF0000',
  us: '#0A3161',
  kr: '#003478',
  fr: '#0032A0',
  za: '#007A4D',
  dz: '#006233',
  au: '#00008B',
  nz: '#00247D',
  ch: '#CC0000',
  ec: '#FFD100',
  se: '#006AA7',
  cz: '#D7141A',
  hr: '#CC0000',
  sa: '#006C35',
  tn: '#E70013',
  tr: '#E30A17',
  sn: '#00A859',
  be: '#EF2B2D',
  ma: '#C1272D',
  at: '#ED2939',
  co: '#C39900',
  eg: '#CE1126',
  ca: '#CC0000',
  ht: '#00209F',
  ir: '#239F40',
  ba: '#002395',
  pa: '#003082',
  cv: '#003893',
  cd: '#007FFF',
  ci: '#CC5500',
  qa: '#8D153A',
  jo: '#555555',
  iq: '#CC0001',
  uz: '#1EB53A',
  nl: '#C05A00',
  no: '#EF2B2D',
  'gb-sct': '#003087',
  cuw: '#555555',
}

export const STRIKERS: Striker[] = [
  // ── URUGUAY ─────────────────────────────────
  { name: "Federico Valverde", country: "Uruguay", code: 'uy' },
  { name: "Giorgian De Arrascaeta", country: "Uruguay", code: 'uy' },
  { name: "Rodrigo Bentancur", country: "Uruguay", code: 'uy' },
  { name: "Manuel Ugarte", country: "Uruguay", code: 'uy' },
  { name: "Brian Rodríguez", country: "Uruguay", code: 'uy' },
  { name: "Rodrigo Zalazar", country: "Uruguay", code: 'uy' },
  { name: "Facundo Pellistri", country: "Uruguay", code: 'uy' },
  { name: "Emiliano Martínez", country: "Uruguay", code: 'uy' },
  { name: "Juan Sanabria", country: "Uruguay", code: 'uy' },
  { name: "Nicolas de la Cruz", country: "Uruguay", code: 'uy' },
  { name: "Rodrigo Aguirre", country: "Uruguay", code: 'uy' },
  { name: "Darwin Núñez", country: "Uruguay", code: 'uy' },
  { name: "Agustín Canobbio", country: "Uruguay", code: 'uy' },
  { name: "Federico Viñas", country: "Uruguay", code: 'uy' },

  // ── GERMANY ─────────────────────────────────
  { name: "Nadiem Amiri", country: "Germany", code: 'de' },
  { name: "Joshua Kimmich", country: "Germany", code: 'de' },
  { name: "Leon Goretzka", country: "Germany", code: 'de' },
  { name: "Pascal Groß", country: "Germany", code: 'de' },
  { name: "Florian Wirtz", country: "Germany", code: 'de' },
  { name: "Felix Kalu Nmecha", country: "Germany", code: 'de' },
  { name: "Angelo Stiller", country: "Germany", code: 'de' },
  { name: "Jamal Musiala", country: "Germany", code: 'de' },
  { name: "Aleksandar Pavlović", country: "Germany", code: 'de' },
  { name: "Assan Ouédraogo", country: "Germany", code: 'de' },
  { name: "Kai Havertz", country: "Germany", code: 'de' },
  { name: "Leroy Sané", country: "Germany", code: 'de' },
  { name: "Deniz Undav", country: "Germany", code: 'de' },
  { name: "Jamie Leweling", country: "Germany", code: 'de' },
  { name: "Nick Woltemade", country: "Germany", code: 'de' },
  { name: "Maximilian Beier", country: "Germany", code: 'de' },

  // ── SPAIN ───────────────────────────────────
  { name: "Fabián Ruiz", country: "Spain", code: 'es' },
  { name: "Marcos Llorente", country: "Spain", code: 'es' },
  { name: "Rodri", country: "Spain", code: 'es' },
  { name: "Mikel Merino", country: "Spain", code: 'es' },
  { name: "Dani Olmo", country: "Spain", code: 'es' },
  { name: "Ferrán Torres", country: "Spain", code: 'es' },
  { name: "Martín Zubimendi", country: "Spain", code: 'es' },
  { name: "Pedri", country: "Spain", code: 'es' },
  { name: "Pablo Gavira", country: "Spain", code: 'es' },
  { name: "Mikel Oyarzabal", country: "Spain", code: 'es' },
  { name: "Álex Baena", country: "Spain", code: 'es' },
  { name: "Borja Iglesias", country: "Spain", code: 'es' },
  { name: "Yeremi Pino", country: "Spain", code: 'es' },
  { name: "Nico Williams", country: "Spain", code: 'es' },
  { name: "Lamine Yamal", country: "Spain", code: 'es' },
  { name: "Víctor Muñoz", country: "Spain", code: 'es' },

  // ── PARAGUAY ────────────────────────────────
  { name: "Andrés Cubas", country: "Paraguay", code: 'py' },
  { name: "Kaku", country: "Paraguay", code: 'py' },
  { name: "Miguel Almirón", country: "Paraguay", code: 'py' },
  { name: "Mauricio", country: "Paraguay", code: 'py' },
  { name: "Braian Ojeda", country: "Paraguay", code: 'py' },
  { name: "Matías Galarza", country: "Paraguay", code: 'py' },
  { name: "Damian Bobadilla", country: "Paraguay", code: 'py' },
  { name: "Diego Gómez", country: "Paraguay", code: 'py' },
  { name: "Antonio Sanabria", country: "Paraguay", code: 'py' },
  { name: "Gabriel Ávalos", country: "Paraguay", code: 'py' },
  { name: "Isidro Pitta", country: "Paraguay", code: 'py' },
  { name: "Ramón Sosa", country: "Paraguay", code: 'py' },
  { name: "Julio Enciso", country: "Paraguay", code: 'py' },
  { name: "Gustavo Caballero", country: "Paraguay", code: 'py' },
  { name: "Alex Arce", country: "Paraguay", code: 'py' },

  // ── ARGENTINA ───────────────────────────────
  { name: "Rodrigo de Paul", country: "Argentina", code: 'ar' },
  { name: "Leandro Paredes", country: "Argentina", code: 'ar' },
  { name: "Giovani Lo Celso", country: "Argentina", code: 'ar' },
  { name: "Exequiel Palacios", country: "Argentina", code: 'ar' },
  { name: "Alexis Mac Allister", country: "Argentina", code: 'ar' },
  { name: "Thiago Almada", country: "Argentina", code: 'ar' },
  { name: "Enzo Fernández", country: "Argentina", code: 'ar' },
  { name: "Nico Paz", country: "Argentina", code: 'ar' },
  { name: "Lionel Messi", country: "Argentina", code: 'ar' },
  { name: "Lautaro Martínez", country: "Argentina", code: 'ar' },
  { name: "Nicolás González", country: "Argentina", code: 'ar' },
  { name: "Julián Álvarez", country: "Argentina", code: 'ar' },
  { name: "José Manuel López", country: "Argentina", code: 'ar' },
  { name: "Giuliano Simeone", country: "Argentina", code: 'ar' },

  // ── GHANA ───────────────────────────────────
  { name: "Thomas Partey", country: "Ghana", code: 'gh' },
  { name: "Elisha Owusu", country: "Ghana", code: 'gh' },
  { name: "Kwasi Sibo", country: "Ghana", code: 'gh' },
  { name: "Augustine Boakye", country: "Ghana", code: 'gh' },
  { name: "Caleb Yirenkyi", country: "Ghana", code: 'gh' },
  { name: "Antoine Semenyo", country: "Ghana", code: 'gh' },
  { name: "Brandon Thomas-Asante", country: "Ghana", code: 'gh' },
  { name: "Jordan Ayew", country: "Ghana", code: 'gh' },
  { name: "Iñaki Williams", country: "Ghana", code: 'gh' },
  { name: "Kamal Deen Sulemana", country: "Ghana", code: 'gh' },
  { name: "Ernest Nuamah", country: "Ghana", code: 'gh' },
  { name: "Abdul Issahaku", country: "Ghana", code: 'gh' },
  { name: "Christopher Bonsu Baah", country: "Ghana", code: 'gh' },
  { name: "Prince Adu", country: "Ghana", code: 'gh' },

  // ── BRAZIL ──────────────────────────────────
  { name: "Lucas Paquetá", country: "Brazil", code: 'br' },
  { name: "Bruno Guimarães", country: "Brazil", code: 'br' },
  { name: "Casemiro", country: "Brazil", code: 'br' },
  { name: "Fabinho", country: "Brazil", code: 'br' },
  { name: "Danilo dos Santos de Oliveira", country: "Brazil", code: 'br' },
  { name: "Vinicius Junior", country: "Brazil", code: 'br' },
  { name: "Neymar", country: "Brazil", code: 'br' },
  { name: "Matheus Cunha", country: "Brazil", code: 'br' },
  { name: "Raphinha", country: "Brazil", code: 'br' },
  { name: "Martinelli", country: "Brazil", code: 'br' },
  { name: "Thiago", country: "Brazil", code: 'br' },
  { name: "Luiz Henrique", country: "Brazil", code: 'br' },
  { name: "Endrick", country: "Brazil", code: 'br' },
  { name: "Rayan", country: "Brazil", code: 'br' },

  // ── PORTUGAL ────────────────────────────────
  { name: "Bernardo Silva", country: "Portugal", code: 'pt' },
  { name: "Rúben Neves", country: "Portugal", code: 'pt' },
  { name: "Bruno Fernandes", country: "Portugal", code: 'pt' },
  { name: "Gonçalo Guedes", country: "Portugal", code: 'pt' },
  { name: "Samuel Almeida Costa", country: "Portugal", code: 'pt' },
  { name: "Vitinha", country: "Portugal", code: 'pt' },
  { name: "Joao Neves", country: "Portugal", code: 'pt' },
  { name: "Cristiano Ronaldo", country: "Portugal", code: 'pt' },
  { name: "Pedro Neto", country: "Portugal", code: 'pt' },
  { name: "Rafael Leão", country: "Portugal", code: 'pt' },
  { name: "Trincão", country: "Portugal", code: 'pt' },
  { name: "João Félix", country: "Portugal", code: 'pt' },
  { name: "Gonçalo Ramos", country: "Portugal", code: 'pt' },
  { name: "Francisco Conceição", country: "Portugal", code: 'pt' },

  // ── JAPAN ───────────────────────────────────
  { name: "Wataru Endō", country: "Japan", code: 'jp' },
  { name: "Daichi Kamada", country: "Japan", code: 'jp' },
  { name: "Takefusa Kubo", country: "Japan", code: 'jp' },
  { name: "Keito Nakamura", country: "Japan", code: 'jp' },
  { name: "Ao Tanaka", country: "Japan", code: 'jp' },
  { name: "Kaishu Sano", country: "Japan", code: 'jp' },
  { name: "Yuito Suzuki", country: "Japan", code: 'jp' },
  { name: "Ritsu Doan", country: "Japan", code: 'jp' },
  { name: "Daizen Maeda", country: "Japan", code: 'jp' },
  { name: "Koki Ogawa", country: "Japan", code: 'jp' },
  { name: "Junya Ito", country: "Japan", code: 'jp' },
  { name: "Ayase Ueda", country: "Japan", code: 'jp' },
  { name: "Kento Shiogai", country: "Japan", code: 'jp' },
  { name: "Keisuke Goto", country: "Japan", code: 'jp' },

  // ── MEXICO ──────────────────────────────────
  { name: "Edson Álvarez", country: "Mexico", code: 'mx' },
  { name: "Orbelín Pineda", country: "Mexico", code: 'mx' },
  { name: "Luis Chávez", country: "Mexico", code: 'mx' },
  { name: "Luis Romo", country: "Mexico", code: 'mx' },
  { name: "Erik Lira", country: "Mexico", code: 'mx' },
  { name: "Álvaro Fidalgo", country: "Mexico", code: 'mx' },
  { name: "Brian Gutiérrez", country: "Mexico", code: 'mx' },
  { name: "Obed Vargas", country: "Mexico", code: 'mx' },
  { name: "Gilberto Mora", country: "Mexico", code: 'mx' },
  { name: "Raúl Jiménez", country: "Mexico", code: 'mx' },
  { name: "Julián Quiñones", country: "Mexico", code: 'mx' },
  { name: "Roberto Alvarado", country: "Mexico", code: 'mx' },
  { name: "Santiago Giménez", country: "Mexico", code: 'mx' },
  { name: "Alexis Vega", country: "Mexico", code: 'mx' },
  { name: "Guillermo Martínez", country: "Mexico", code: 'mx' },
  { name: "César Huerta", country: "Mexico", code: 'mx' },
  { name: "Armando González", country: "Mexico", code: 'mx' },

  // ── ENGLAND ─────────────────────────────────
  { name: "Jordan Henderson", country: "England", code: 'gb-eng' },
  { name: "Eberechi Eze", country: "England", code: 'gb-eng' },
  { name: "Anthony Gordon", country: "England", code: 'gb-eng' },
  { name: "Declan Rice", country: "England", code: 'gb-eng' },
  { name: "Morgan Rogers", country: "England", code: 'gb-eng' },
  { name: "Elliot Anderson", country: "England", code: 'gb-eng' },
  { name: "Jude Bellingham", country: "England", code: 'gb-eng' },
  { name: "Kobbie Mainoo", country: "England", code: 'gb-eng' },
  { name: "Marcus Rashford", country: "England", code: 'gb-eng' },
  { name: "Ollie Watkins", country: "England", code: 'gb-eng' },
  { name: "Ivan Toney", country: "England", code: 'gb-eng' },
  { name: "Harry Kane", country: "England", code: 'gb-eng' },
  { name: "Bukayo Saka", country: "England", code: 'gb-eng' },
  { name: "Noni Madueke", country: "England", code: 'gb-eng' },

  // ── UNITED STATES ───────────────────────────
  { name: "Weston McKennie", country: "United States", code: 'us' },
  { name: "Alejandro Zendejas", country: "United States", code: 'us' },
  { name: "Cristian Roldan", country: "United States", code: 'us' },
  { name: "Tyler Adams", country: "United States", code: 'us' },
  { name: "Brenden Aaronson", country: "United States", code: 'us' },
  { name: "Gio Reyna", country: "United States", code: 'us' },
  { name: "Sebastian Berhalter", country: "United States", code: 'us' },
  { name: "Malik Tillman", country: "United States", code: 'us' },
  { name: "Christian Pulisic", country: "United States", code: 'us' },
  { name: "Tim Weah", country: "United States", code: 'us' },
  { name: "Haji Wright", country: "United States", code: 'us' },
  { name: "Ricardo Pepi", country: "United States", code: 'us' },
  { name: "Folarin Balogun", country: "United States", code: 'us' },
  { name: "Max Arfsten", country: "United States", code: 'us' },

  // ── SOUTH KOREA ─────────────────────────────
  { name: "Jens Castrop", country: "South Korea", code: 'kr' },
  { name: "In-beom Hwang", country: "South Korea", code: 'kr' },
  { name: "Dong-gyeong Lee", country: "South Korea", code: 'kr' },
  { name: "Jae-sung Lee", country: "South Korea", code: 'kr' },
  { name: "Jin-Gyu Kim", country: "South Korea", code: 'kr' },
  { name: "Seung-Ho Paik", country: "South Korea", code: 'kr' },
  { name: "Kang-in Lee", country: "South Korea", code: 'kr' },
  { name: "Joon-ho Bae", country: "South Korea", code: 'kr' },
  { name: "Hwang Heechan", country: "South Korea", code: 'kr' },
  { name: "Heung-min Son", country: "South Korea", code: 'kr' },
  { name: "Hyun-jun Yang", country: "South Korea", code: 'kr' },
  { name: "Gue-Sung Cho", country: "South Korea", code: 'kr' },
  { name: "Hyun-Gyu Oh", country: "South Korea", code: 'kr' },
  { name: "Ji-sung Eom", country: "South Korea", code: 'kr' },

  // ── FRANCE ──────────────────────────────────
  { name: "N'Golo Kanté", country: "France", code: 'fr' },
  { name: "Adrien Rabiot", country: "France", code: 'fr' },
  { name: "Aurélien Tchouameni", country: "France", code: 'fr' },
  { name: "Manu Koné", country: "France", code: 'fr' },
  { name: "Rayan Cherki", country: "France", code: 'fr' },
  { name: "Maghnes Akliouche", country: "France", code: 'fr' },
  { name: "Desire Doue", country: "France", code: 'fr' },
  { name: "Warren Zaïre-Emery", country: "France", code: 'fr' },
  { name: "Jean-Philippe Mateta", country: "France", code: 'fr' },
  { name: "Ousmane Dembélé", country: "France", code: 'fr' },
  { name: "Kylian Mbappé", country: "France", code: 'fr' },
  { name: "Marcus Thuram-Ulien", country: "France", code: 'fr' },
  { name: "Michael Olise", country: "France", code: 'fr' },
  { name: "Bradley Barcola", country: "France", code: 'fr' },

  // ── SOUTH AFRICA ────────────────────────────
  { name: "Themba Zwane", country: "South Africa", code: 'za' },
  { name: "Teboho Mokoena", country: "South Africa", code: 'za' },
  { name: "Sphephelo Sithole", country: "South Africa", code: 'za' },
  { name: "Jayden Adams", country: "South Africa", code: 'za' },
  { name: "Thapelo Maseko", country: "South Africa", code: 'za' },
  { name: "Thalente Mbatha", country: "South Africa", code: 'za' },
  { name: "Kamogelo Sebelebele", country: "South Africa", code: 'za' },
  { name: "Lyle Foster", country: "South Africa", code: 'za' },
  { name: "Oswin Appollis", country: "South Africa", code: 'za' },
  { name: "Iqraam Rayners", country: "South Africa", code: 'za' },
  { name: "Evidence Makgopa", country: "South Africa", code: 'za' },
  { name: "Relebohile Mofokeng", country: "South Africa", code: 'za' },
  { name: "Tshepang Moremi", country: "South Africa", code: 'za' },

  // ── ALGERIA ─────────────────────────────────
  { name: "Nabil Bentaleb", country: "Algeria", code: 'dz' },
  { name: "Houssem Aouar", country: "Algeria", code: 'dz' },
  { name: "Hicham Boudaoui", country: "Algeria", code: 'dz' },
  { name: "Ramiz Zerrouki", country: "Algeria", code: 'dz' },
  { name: "Fares Chaïbi", country: "Algeria", code: 'dz' },
  { name: "Ibrahim Maza", country: "Algeria", code: 'dz' },
  { name: "Yacine Titraoui", country: "Algeria", code: 'dz' },
  { name: "Adil Boulbina", country: "Algeria", code: 'dz' },
  { name: "Riyad Mahrez", country: "Algeria", code: 'dz' },
  { name: "Amine Gouiri", country: "Algeria", code: 'dz' },
  { name: "Mohammed Amoura", country: "Algeria", code: 'dz' },
  { name: "Nadhir Benbouali", country: "Algeria", code: 'dz' },
  { name: "Anis Moussa", country: "Algeria", code: 'dz' },
  { name: "Farés Ghedjemis", country: "Algeria", code: 'dz' },

  // ── AUSTRALIA ───────────────────────────────
  { name: "Mathew Leckie", country: "Australia", code: 'au' },
  { name: "Jackson Irvine", country: "Australia", code: 'au' },
  { name: "Connor Metcalfe", country: "Australia", code: 'au' },
  { name: "Ajdin Hrustic", country: "Australia", code: 'au' },
  { name: "Aiden O'Neill", country: "Australia", code: 'au' },
  { name: "Awer Mabil", country: "Australia", code: 'au' },
  { name: "Cameron Devlin", country: "Australia", code: 'au' },
  { name: "Paul Okon-Engstler", country: "Australia", code: 'au' },
  { name: "Mohamed Toure", country: "Australia", code: 'au' },
  { name: "Nishan Velupillay", country: "Australia", code: 'au' },
  { name: "Cristian Volpato", country: "Australia", code: 'au' },
  { name: "Nestor Irankunda", country: "Australia", code: 'au' },
  { name: "Tete Yengi", country: "Australia", code: 'au' },

  // ── NEW ZEALAND ─────────────────────────────
  { name: "Alex Rufer", country: "New Zealand", code: 'nz' },
  { name: "Sarpreet Singh", country: "New Zealand", code: 'nz' },
  { name: "Ryan Thomas", country: "New Zealand", code: 'nz' },
  { name: "Callum McCowatt", country: "New Zealand", code: 'nz' },
  { name: "Joe Bell", country: "New Zealand", code: 'nz' },
  { name: "Marko Stamenic", country: "New Zealand", code: 'nz' },
  { name: "Ben Old", country: "New Zealand", code: 'nz' },
  { name: "Kosta Barbarouses", country: "New Zealand", code: 'nz' },
  { name: "Chris Wood", country: "New Zealand", code: 'nz' },
  { name: "Ben Waine", country: "New Zealand", code: 'nz' },
  { name: "Elijah Just", country: "New Zealand", code: 'nz' },
  { name: "Matthew Garbett", country: "New Zealand", code: 'nz' },
  { name: "Lachlan Bayliss", country: "New Zealand", code: 'nz' },
  { name: "Jesse Randall", country: "New Zealand", code: 'nz' },

  // ── SWITZERLAND ─────────────────────────────
  { name: "Remo Freuler", country: "Switzerland", code: 'ch' },
  { name: "Granit Xhaka", country: "Switzerland", code: 'ch' },
  { name: "Denis Zakaria", country: "Switzerland", code: 'ch' },
  { name: "Michel Aebischer", country: "Switzerland", code: 'ch' },
  { name: "Djibril Sow", country: "Switzerland", code: 'ch' },
  { name: "Christian Fassnacht", country: "Switzerland", code: 'ch' },
  { name: "Ruben Vargas", country: "Switzerland", code: 'ch' },
  { name: "Ardon Jasari", country: "Switzerland", code: 'ch' },
  { name: "Fabian Rieder", country: "Switzerland", code: 'ch' },
  { name: "Johan Manzambi", country: "Switzerland", code: 'ch' },
  { name: "Breel Embolo", country: "Switzerland", code: 'ch' },
  { name: "Noah Okafor", country: "Switzerland", code: 'ch' },
  { name: "Cédric Itten", country: "Switzerland", code: 'ch' },
  { name: "Dan Ndoye", country: "Switzerland", code: 'ch' },
  { name: "Zeki Amdouni", country: "Switzerland", code: 'ch' },

  // ── ECUADOR ─────────────────────────────────
  { name: "Alan Franco", country: "Ecuador", code: 'ec' },
  { name: "Jordy Alcívar", country: "Ecuador", code: 'ec' },
  { name: "Gonzalo Plata", country: "Ecuador", code: 'ec' },
  { name: "Moisés Caicedo", country: "Ecuador", code: 'ec' },
  { name: "Pedro Vite", country: "Ecuador", code: 'ec' },
  { name: "Alan Minda", country: "Ecuador", code: 'ec' },
  { name: "Ray Paez", country: "Ecuador", code: 'ec' },
  { name: "Denil Castillo", country: "Ecuador", code: 'ec' },
  { name: "Jordy Caicedo", country: "Ecuador", code: 'ec' },
  { name: "Enner Valencia", country: "Ecuador", code: 'ec' },
  { name: "John Yeboah", country: "Ecuador", code: 'ec' },
  { name: "Anthony Valencia", country: "Ecuador", code: 'ec' },
  { name: "Nilson Angulo", country: "Ecuador", code: 'ec' },
  { name: "Kevin Rodríguez", country: "Ecuador", code: 'ec' },
  { name: "Jeremy", country: "Ecuador", code: 'ec' },

  // ── SWEDEN ──────────────────────────────────
  { name: "Ken Sema", country: "Sweden", code: 'se' },
  { name: "Mattias Svanberg", country: "Sweden", code: 'se' },
  { name: "Jesper Karlström", country: "Sweden", code: 'se' },
  { name: "Yasin Ayari", country: "Sweden", code: 'se' },
  { name: "Besfort Zeneli", country: "Sweden", code: 'se' },
  { name: "Taha Ali", country: "Sweden", code: 'se' },
  { name: "Lucas Bergvall", country: "Sweden", code: 'se' },
  { name: "Alexander Isak", country: "Sweden", code: 'se' },
  { name: "Viktor Gyökeres", country: "Sweden", code: 'se' },
  { name: "Gustaf Nilsson", country: "Sweden", code: 'se' },
  { name: "Benjamin Nygren", country: "Sweden", code: 'se' },
  { name: "Alexander Bernhardsson", country: "Sweden", code: 'se' },
  { name: "Anthony Elanga", country: "Sweden", code: 'se' },

  // ── CZECHIA ─────────────────────────────────
  { name: "Vladimír Darida", country: "Czechia", code: 'cz' },
  { name: "Tomáš Souček", country: "Czechia", code: 'cz' },
  { name: "David Douděra", country: "Czechia", code: 'cz' },
  { name: "Michal Sadílek", country: "Czechia", code: 'cz' },
  { name: "Lukáš Provod", country: "Czechia", code: 'cz' },
  { name: "Pavel Šulc", country: "Czechia", code: 'cz' },
  { name: "Lukáš Červ", country: "Czechia", code: 'cz' },
  { name: "Denis Višinský", country: "Czechia", code: 'cz' },
  { name: "Alexandr Sojka", country: "Czechia", code: 'cz' },
  { name: "Hugo Sochůrek", country: "Czechia", code: 'cz' },
  { name: "Patrik Schick", country: "Czechia", code: 'cz' },
  { name: "Tomáš Chorý", country: "Czechia", code: 'cz' },
  { name: "Jan Kuchta", country: "Czechia", code: 'cz' },
  { name: "Adam Hložek", country: "Czechia", code: 'cz' },
  { name: "Mojmír Chytil", country: "Czechia", code: 'cz' },

  // ── CROATIA ─────────────────────────────────
  { name: "Luka Modrić", country: "Croatia", code: 'hr' },
  { name: "Mateo Kovačić", country: "Croatia", code: 'hr' },
  { name: "Mario Pašalić", country: "Croatia", code: 'hr' },
  { name: "Nikola Vlašić", country: "Croatia", code: 'hr' },
  { name: "Nikola Moro", country: "Croatia", code: 'hr' },
  { name: "Kristijan Jakić", country: "Croatia", code: 'hr' },
  { name: "Luka Sučić", country: "Croatia", code: 'hr' },
  { name: "Petar Sucic", country: "Croatia", code: 'hr' },
  { name: "Martin Baturina", country: "Croatia", code: 'hr' },
  { name: "Toni Fruk", country: "Croatia", code: 'hr' },
  { name: "Andrej Kramarić", country: "Croatia", code: 'hr' },
  { name: "Ivan Perišić", country: "Croatia", code: 'hr' },
  { name: "Ante Budimir", country: "Croatia", code: 'hr' },
  { name: "Petar Musa", country: "Croatia", code: 'hr' },
  { name: "Marco Pašalić", country: "Croatia", code: 'hr' },
  { name: "Igor Matanovic", country: "Croatia", code: 'hr' },

  // ── SAUDI ARABIA ────────────────────────────
  { name: "Salem Al Dawsari", country: "Saudi Arabia", code: 'sa' },
  { name: "Abdullah Al Khaibari", country: "Saudi Arabia", code: 'sa' },
  { name: "Nasser Al Dawsari", country: "Saudi Arabia", code: 'sa' },
  { name: "Ayman Yahya", country: "Saudi Arabia", code: 'sa' },
  { name: "Musab Al Juwayr", country: "Saudi Arabia", code: 'sa' },
  { name: "Mohammed Kanno", country: "Saudi Arabia", code: 'sa' },
  { name: "Ziyad Al-Johani", country: "Saudi Arabia", code: 'sa' },
  { name: "Mohammed Abu Al Shamat", country: "Saudi Arabia", code: 'sa' },
  { name: "Alaa Al Hejji", country: "Saudi Arabia", code: 'sa' },
  { name: "Sultan Mandash", country: "Saudi Arabia", code: 'sa' },
  { name: "Saleh Al Shehri", country: "Saudi Arabia", code: 'sa' },
  { name: "Abdullah Al-Hamdan", country: "Saudi Arabia", code: 'sa' },
  { name: "Khalid Al Ghannam", country: "Saudi Arabia", code: 'sa' },
  { name: "Firas Al Brikan", country: "Saudi Arabia", code: 'sa' },

  // ── TUNISIA ─────────────────────────────────
  { name: "Ellyes Skhiri", country: "Tunisia", code: 'tn' },
  { name: "Rani Khedira", country: "Tunisia", code: 'tn' },
  { name: "Anis Ben Slimane", country: "Tunisia", code: 'tn' },
  { name: "Ismaël Gharbi", country: "Tunisia", code: 'tn' },
  { name: "Hannibal Mejbri", country: "Tunisia", code: 'tn' },
  { name: "Elias Achouri", country: "Tunisia", code: 'tn' },
  { name: "Hadj Mahmoud", country: "Tunisia", code: 'tn' },
  { name: "Sebastian Tounekti", country: "Tunisia", code: 'tn' },
  { name: "Firas Chaouat", country: "Tunisia", code: 'tn' },
  { name: "Elias Saad", country: "Tunisia", code: 'tn' },
  { name: "Hazem Mastouri", country: "Tunisia", code: 'tn' },
  { name: "Rayan Elloumi", country: "Tunisia", code: 'tn' },
  { name: "Khalil Ayari", country: "Tunisia", code: 'tn' },

  // ── TURKEY ──────────────────────────────────
  { name: "Salih Özcan", country: "Turkey", code: 'tr' },
  { name: "Hakan Çalhanoğlu", country: "Turkey", code: 'tr' },
  { name: "Orkun Kökçü", country: "Turkey", code: 'tr' },
  { name: "İsmail Yüksek", country: "Turkey", code: 'tr' },
  { name: "Arda Guler", country: "Turkey", code: 'tr' },
  { name: "Oguz Aydin", country: "Turkey", code: 'tr' },
  { name: "Baris Yilmaz", country: "Turkey", code: 'tr' },
  { name: "İrfan Kahveci", country: "Turkey", code: 'tr' },
  { name: "Yunus Akgün", country: "Turkey", code: 'tr' },
  { name: "Muhammed Kerem Aktürkoğlu", country: "Turkey", code: 'tr' },
  { name: "Deniz Gul", country: "Turkey", code: 'tr' },
  { name: "Kenan Yıldız", country: "Turkey", code: 'tr' },
  { name: "Can Uzun", country: "Turkey", code: 'tr' },

  // ── SENEGAL ─────────────────────────────────
  { name: "Pape Gueye", country: "Senegal", code: 'sn' },
  { name: "Idrissa Gana Guèye", country: "Senegal", code: 'sn' },
  { name: "Ismaïla Sarr", country: "Senegal", code: 'sn' },
  { name: "Krépin Diatta", country: "Senegal", code: 'sn' },
  { name: "Pathé Ciss", country: "Senegal", code: 'sn' },
  { name: "Iliman Ndiaye", country: "Senegal", code: 'sn' },
  { name: "Pape Sarr", country: "Senegal", code: 'sn' },
  { name: "Habib Diarra", country: "Senegal", code: 'sn' },
  { name: "Lamine Camara", country: "Senegal", code: 'sn' },
  { name: "Bara Ndiaye", country: "Senegal", code: 'sn' },
  { name: "Sadio Mané", country: "Senegal", code: 'sn' },
  { name: "Cherif Ndiaye", country: "Senegal", code: 'sn' },
  { name: "Nicolas Jackson", country: "Senegal", code: 'sn' },
  { name: "Ahmadou Bamba Dieng", country: "Senegal", code: 'sn' },
  { name: "Assane Diao", country: "Senegal", code: 'sn' },
  { name: "Ibrahim M'Baye", country: "Senegal", code: 'sn' },

  // ── BELGIUM ─────────────────────────────────
  { name: "Kevin De Bruyne", country: "Belgium", code: 'be' },
  { name: "Axel Witsel", country: "Belgium", code: 'be' },
  { name: "Youri Tielemans", country: "Belgium", code: 'be' },
  { name: "Dodi Lukebakio", country: "Belgium", code: 'be' },
  { name: "Alexis Saelemaekers", country: "Belgium", code: 'be' },
  { name: "Hans Vanaken", country: "Belgium", code: 'be' },
  { name: "Nicolas Raskin", country: "Belgium", code: 'be' },
  { name: "Jeremy Doku", country: "Belgium", code: 'be' },
  { name: "Amadou Onana", country: "Belgium", code: 'be' },
  { name: "Diego Moreira", country: "Belgium", code: 'be' },
  { name: "Romelu Lukaku", country: "Belgium", code: 'be' },
  { name: "Leandro Trossard", country: "Belgium", code: 'be' },
  { name: "Charles De Ketelaere", country: "Belgium", code: 'be' },
  { name: "Matias Fernandez-Pardo", country: "Belgium", code: 'be' },

  // ── MOROCCO ─────────────────────────────────
  { name: "Sofyan Amrabat", country: "Morocco", code: 'ma' },
  { name: "Brahim Diaz", country: "Morocco", code: 'ma' },
  { name: "Azzedine Ounahi", country: "Morocco", code: 'ma' },
  { name: "Ismael Saibari", country: "Morocco", code: 'ma' },
  { name: "Neil El Aynaoui", country: "Morocco", code: 'ma' },
  { name: "Bilal El Khannouss", country: "Morocco", code: 'ma' },
  { name: "Chemsdine Talbi", country: "Morocco", code: 'ma' },
  { name: "Ayyoub Bouaddi", country: "Morocco", code: 'ma' },
  { name: "Samir El Mourabet", country: "Morocco", code: 'ma' },
  { name: "Soufiane Rahimi", country: "Morocco", code: 'ma' },
  { name: "Ayoub El Kaabi", country: "Morocco", code: 'ma' },
  { name: "Abdessamad Ezzalzouli", country: "Morocco", code: 'ma' },
  { name: "Gessime Yassine", country: "Morocco", code: 'ma' },
  { name: "Ayoube Amaimouni-Echghouyab", country: "Morocco", code: 'ma' },

  // ── AUSTRIA ─────────────────────────────────
  { name: "Florian Grillitsch", country: "Austria", code: 'at' },
  { name: "Alessandro Schöpf", country: "Austria", code: 'at' },
  { name: "Konrad Laimer", country: "Austria", code: 'at' },
  { name: "Marcel Sabitzer", country: "Austria", code: 'at' },
  { name: "Xaver Schlager", country: "Austria", code: 'at' },
  { name: "Romano Schmid", country: "Austria", code: 'at' },
  { name: "Christoph Baumgartner", country: "Austria", code: 'at' },
  { name: "Nicolas  Seiwald", country: "Austria", code: 'at' },
  { name: "Patrick Wimmer", country: "Austria", code: 'at' },
  { name: "Carney Chukwuemeka", country: "Austria", code: 'at' },
  { name: "Paul Wanner", country: "Austria", code: 'at' },
  { name: "Michael Gregoritsch", country: "Austria", code: 'at' },
  { name: "Marko Arnautovic", country: "Austria", code: 'at' },
  { name: "Saša Kalajdžić", country: "Austria", code: 'at' },

  // ── COLOMBIA ────────────────────────────────
  { name: "James Rodríguez", country: "Colombia", code: 'co' },
  { name: "Jefferson Lerma", country: "Colombia", code: 'co' },
  { name: "Jhon Arias", country: "Colombia", code: 'co' },
  { name: "Jorge Carrascal", country: "Colombia", code: 'co' },
  { name: "Kevin Castaño", country: "Colombia", code: 'co' },
  { name: "Juan Quintero", country: "Colombia", code: 'co' },
  { name: "Jaminton Campaz", country: "Colombia", code: 'co' },
  { name: "Richard Rios", country: "Colombia", code: 'co' },
  { name: "Juan Portilla", country: "Colombia", code: 'co' },
  { name: "Gustavo Puerta", country: "Colombia", code: 'co' },
  { name: "Jhon Córdoba", country: "Colombia", code: 'co' },
  { name: "Luis Díaz", country: "Colombia", code: 'co' },
  { name: "Luis Suárez", country: "Colombia", code: 'co' },
  { name: "Cucho Hernández", country: "Colombia", code: 'co' },
  { name: "Carlos Gómez", country: "Colombia", code: 'co' },

  // ── EGYPT ───────────────────────────────────
  { name: "Zizo", country: "Egypt", code: 'eg' },
  { name: "Nabil Dunga", country: "Egypt", code: 'eg' },
  { name: "Hamdy Fathy", country: "Egypt", code: 'eg' },
  { name: "Trezeguet", country: "Egypt", code: 'eg' },
  { name: "Emam Ashour", country: "Egypt", code: 'eg' },
  { name: "Mohanad Lashin", country: "Egypt", code: 'eg' },
  { name: "Marwan Attia", country: "Egypt", code: 'eg' },
  { name: "Mahmoud Saber", country: "Egypt", code: 'eg' },
  { name: "Mostafa Ziko", country: "Egypt", code: 'eg' },
  { name: "Mohamed Salah", country: "Egypt", code: 'eg' },
  { name: "Omar Marmoush", country: "Egypt", code: 'eg' },
  { name: "Haissem Hassan", country: "Egypt", code: 'eg' },
  { name: "Ibrahim Adel", country: "Egypt", code: 'eg' },
  { name: "Hamza Abdelkarim", country: "Egypt", code: 'eg' },

  // ── CANADA ──────────────────────────────────
  { name: "Jonathan Osorio", country: "Canada", code: 'ca' },
  { name: "Stephen Eustáquio", country: "Canada", code: 'ca' },
  { name: "Mathieu Choinière", country: "Canada", code: 'ca' },
  { name: "Tajon Buchanan", country: "Canada", code: 'ca' },
  { name: "Marcelo Flores", country: "Canada", code: 'ca' },
  { name: "Nathan-Dylan Saliba", country: "Canada", code: 'ca' },
  { name: "Ismael Kone", country: "Canada", code: 'ca' },
  { name: "Ali Ahmed", country: "Canada", code: 'ca' },
  { name: "Niko Sigur", country: "Canada", code: 'ca' },
  { name: "Jonathan David", country: "Canada", code: 'ca' },
  { name: "Cyle Larin", country: "Canada", code: 'ca' },
  { name: "Liam Millar", country: "Canada", code: 'ca' },
  { name: "Jacob Shaffelburg", country: "Canada", code: 'ca' },
  { name: "Tani Oluwaseyi", country: "Canada", code: 'ca' },
  { name: "Promise Akinpelu", country: "Canada", code: 'ca' },

  // ── HAITI ───────────────────────────────────
  { name: "Leverton Pierre", country: "Haiti", code: 'ht' },
  { name: "Jean-Ricner Bellegarde", country: "Haiti", code: 'ht' },
  { name: "Derrick Etienne", country: "Haiti", code: 'ht' },
  { name: "Danley Jean Jacques", country: "Haiti", code: 'ht' },
  { name: "Dominique Simon", country: "Haiti", code: 'ht' },
  { name: "Carl Sainté", country: "Haiti", code: 'ht' },
  { name: "Woodensky Pierre", country: "Haiti", code: 'ht' },
  { name: "Duckens Nazon", country: "Haiti", code: 'ht' },
  { name: "Frantzdy Pierrot", country: "Haiti", code: 'ht' },
  { name: "Yassin Fortune", country: "Haiti", code: 'ht' },
  { name: "Wilson Isidor", country: "Haiti", code: 'ht' },
  { name: "Lenny Joseph", country: "Haiti", code: 'ht' },
  { name: "Louicius Don Deedson", country: "Haiti", code: 'ht' },
  { name: "Josué Casimir", country: "Haiti", code: 'ht' },
  { name: "Ruben Providence", country: "Haiti", code: 'ht' },

  // ── IRAN ────────────────────────────────────
  { name: "Saeid Ezatolahi", country: "Iran", code: 'ir' },
  { name: "Mehdi Torabi", country: "Iran", code: 'ir' },
  { name: "Mohammad Ghorbani", country: "Iran", code: 'ir' },
  { name: "Ariya Yousefi", country: "Iran", code: 'ir' },
  { name: "Medhi Ghayedi", country: "Iran", code: 'ir' },
  { name: "Amir Razzaghinia", country: "Iran", code: 'ir' },
  { name: "Alireza Jahanbakhsh", country: "Iran", code: 'ir' },
  { name: "Mehdi Taremi", country: "Iran", code: 'ir' },
  { name: "Dennis Eckert", country: "Iran", code: 'ir' },
  { name: "Ali Alipour", country: "Iran", code: 'ir' },
  { name: "Shahriar Moghanlou", country: "Iran", code: 'ir' },
  { name: "Mohammad Mohebi", country: "Iran", code: 'ir' },
  { name: "Saman Ghoddos", country: "Iran", code: 'ir' },
  { name: "Amir Hosseinzadeh", country: "Iran", code: 'ir' },

  // ── BOSNIA-HERZEGOVINA ──────────────────────
  { name: "Dženis Burnić", country: "Bosnia-Herzegovina", code: 'ba' },
  { name: "Ivan Šunjić", country: "Bosnia-Herzegovina", code: 'ba' },
  { name: "Amir Hadžiahmetović", country: "Bosnia-Herzegovina", code: 'ba' },
  { name: "Armin Gigovic", country: "Bosnia-Herzegovina", code: 'ba' },
  { name: "Ivan Bašić", country: "Bosnia-Herzegovina", code: 'ba' },
  { name: "Benjamin Tahirovic", country: "Bosnia-Herzegovina", code: 'ba' },
  { name: "Ermin Mahmic", country: "Bosnia-Herzegovina", code: 'ba' },
  { name: "Amar Memić", country: "Bosnia-Herzegovina", code: 'ba' },
  { name: "Edin Džeko", country: "Bosnia-Herzegovina", code: 'ba' },
  { name: "Jovo Lukić", country: "Bosnia-Herzegovina", code: 'ba' },
  { name: "Ermedin Demirovic", country: "Bosnia-Herzegovina", code: 'ba' },
  { name: "Haris Tabaković", country: "Bosnia-Herzegovina", code: 'ba' },
  { name: "Samed Bazdar", country: "Bosnia-Herzegovina", code: 'ba' },
  { name: "Esmir Bajraktarevic", country: "Bosnia-Herzegovina", code: 'ba' },
  { name: "Kerim Alajbegović", country: "Bosnia-Herzegovina", code: 'ba' },

  // ── PANAMA ──────────────────────────────────
  { name: "Adalberto Carrasquilla", country: "Panama", code: 'pa' },
  { name: "José Luis Rodríguez", country: "Panama", code: 'pa' },
  { name: "Cecilio Waterman", country: "Panama", code: 'pa' },
  { name: "Édgar Bárcenas", country: "Panama", code: 'pa' },
  { name: "Aníbal Godoy", country: "Panama", code: 'pa' },
  { name: "Alberto Quintero", country: "Panama", code: 'pa' },
  { name: "Carlos Harvey", country: "Panama", code: 'pa' },
  { name: "César Yanis", country: "Panama", code: 'pa' },
  { name: "Christian Martinez", country: "Panama", code: 'pa' },
  { name: "José Fajardo", country: "Panama", code: 'pa' },
  { name: "Ismael Díaz", country: "Panama", code: 'pa' },
  { name: "Tomas Rodriguez", country: "Panama", code: 'pa' },
  { name: "Azarias Londoño", country: "Panama", code: 'pa' },

  // ── CAPE VERDE ISLANDS ──────────────────────
  { name: "Deroy Duarte", country: "Cape Verde Islands", code: 'cv' },
  { name: "Garry Rodrigues", country: "Cape Verde Islands", code: 'cv' },
  { name: "Kevin Pina", country: "Cape Verde Islands", code: 'cv' },
  { name: "Laros Duarte", country: "Cape Verde Islands", code: 'cv' },
  { name: "Yannick Semedo", country: "Cape Verde Islands", code: 'cv' },
  { name: "Telmo Arcanjo", country: "Cape Verde Islands", code: 'cv' },
  { name: "Jamiro Monteiro", country: "Cape Verde Islands", code: 'cv' },
  { name: "João Paulo", country: "Cape Verde Islands", code: 'cv' },
  { name: "Willy Semedo", country: "Cape Verde Islands", code: 'cv' },
  { name: "Ryan Mendes", country: "Cape Verde Islands", code: 'cv' },
  { name: "Jovane Cabral", country: "Cape Verde Islands", code: 'cv' },
  { name: "Gilson Tavares", country: "Cape Verde Islands", code: 'cv' },
  { name: "Nuno Da Costa", country: "Cape Verde Islands", code: 'cv' },
  { name: "Dailon Rocha Livramento", country: "Cape Verde Islands", code: 'cv' },
  { name: "Hélio Varela", country: "Cape Verde Islands", code: 'cv' },

  // ── CONGO DR ────────────────────────────────
  { name: "Gaël Kakuta", country: "Congo DR", code: 'cd' },
  { name: "Samuel Moutoussamy", country: "Congo DR", code: 'cd' },
  { name: "Edo Kayembe", country: "Congo DR", code: 'cd' },
  { name: "Aaron Tshibola", country: "Congo DR", code: 'cd' },
  { name: "Charles Pickel", country: "Congo DR", code: 'cd' },
  { name: "Noah Sadiki", country: "Congo DR", code: 'cd' },
  { name: "Ngal'ayel Mukau", country: "Congo DR", code: 'cd' },
  { name: "Yoane Wissa", country: "Congo DR", code: 'cd' },
  { name: "Theo Bongonda", country: "Congo DR", code: 'cd' },
  { name: "Cédric Bakambu", country: "Congo DR", code: 'cd' },
  { name: "Simon Banza", country: "Congo DR", code: 'cd' },
  { name: "Nathanael Mbuku", country: "Congo DR", code: 'cd' },
  { name: "Meschack Elia", country: "Congo DR", code: 'cd' },
  { name: "Brian Cipenga", country: "Congo DR", code: 'cd' },
  { name: "Fiston Mayele", country: "Congo DR", code: 'cd' },

  // ── IVORY COAST ─────────────────────────────
  { name: "Franck Kessié", country: "Ivory Coast", code: 'ci' },
  { name: "Seko Fofana", country: "Ivory Coast", code: 'ci' },
  { name: "Ibrahim Sangaré", country: "Ivory Coast", code: 'ci' },
  { name: "Jean Michaël Seri", country: "Ivory Coast", code: 'ci' },
  { name: "Amad Diallo", country: "Ivory Coast", code: 'ci' },
  { name: "Parfait Guiagon", country: "Ivory Coast", code: 'ci' },
  { name: "Christ Ravynel Inao Oulaï", country: "Ivory Coast", code: 'ci' },
  { name: "Nicolas Pépé", country: "Ivory Coast", code: 'ci' },
  { name: "Evann Guessand", country: "Ivory Coast", code: 'ci' },
  { name: "Ange-Yoan Bonny", country: "Ivory Coast", code: 'ci' },
  { name: "Sepe Elye Wahi", country: "Ivory Coast", code: 'ci' },
  { name: "Simon Adingra", country: "Ivory Coast", code: 'ci' },
  { name: "Oumar Diakite", country: "Ivory Coast", code: 'ci' },
  { name: "Bazoumana Touré", country: "Ivory Coast", code: 'ci' },
  { name: "Yan Diomandé", country: "Ivory Coast", code: 'ci' },

  // ── QATAR ───────────────────────────────────
  { name: "Assim Madibo", country: "Qatar", code: 'qa' },
  { name: "Abdulaziz Hatem", country: "Qatar", code: 'qa' },
  { name: "Karim Boudiaf", country: "Qatar", code: 'qa' },
  { name: "Ahmed Fathy", country: "Qatar", code: 'qa' },
  { name: "Yusuf Abdurisag", country: "Qatar", code: 'qa' },
  { name: "Ahmed Al Ganehi", country: "Qatar", code: 'qa' },
  { name: "Tahsin Jamshid", country: "Qatar", code: 'qa' },
  { name: "Mohamed Al-Mannai", country: "Qatar", code: 'qa' },
  { name: "Akram Afif", country: "Qatar", code: 'qa' },
  { name: "Almoez Ali", country: "Qatar", code: 'qa' },
  { name: "Mohammed Muntari", country: "Qatar", code: 'qa' },
  { name: "Hassan Al Haydos", country: "Qatar", code: 'qa' },
  { name: "Ahmed Alaa Eldin", country: "Qatar", code: 'qa' },
  { name: "Edmílson", country: "Qatar", code: 'qa' },

  // ── JORDAN ──────────────────────────────────
  { name: "Nizar Al Rashdan", country: "Jordan", code: 'jo' },
  { name: "Rajaei Ayed", country: "Jordan", code: 'jo' },
  { name: "Noor Al Rawabdeh", country: "Jordan", code: 'jo' },
  { name: "Mohammad Abu Hasheesh", country: "Jordan", code: 'jo' },
  { name: "Ibrahim Saadeh", country: "Jordan", code: 'jo' },
  { name: "Mohammad Al-Dawoud", country: "Jordan", code: 'jo' },
  { name: "Amer Jamous", country: "Jordan", code: 'jo' },
  { name: "Musa Al Taamari", country: "Jordan", code: 'jo' },
  { name: "Mahmoud Al Mardi", country: "Jordan", code: 'jo' },
  { name: "Ali Olwan", country: "Jordan", code: 'jo' },
  { name: "Mohannad Abu Taha", country: "Jordan", code: 'jo' },
  { name: "Mohammad Abu Zrayq", country: "Jordan", code: 'jo' },
  { name: "Ibrahim Sabra", country: "Jordan", code: 'jo' },
  { name: "Odeh Fakhoury", country: "Jordan", code: 'jo' },
  { name: "Ali Azaizeh", country: "Jordan", code: 'jo' },

  // ── IRAQ ────────────────────────────────────
  { name: "Amir Al Ammari", country: "Iraq", code: 'iq' },
  { name: "Kevin Yakob", country: "Iraq", code: 'iq' },
  { name: "Aimar Sher", country: "Iraq", code: 'iq' },
  { name: "Ibrahim Bayesh", country: "Iraq", code: 'iq' },
  { name: "Youssef Amyn", country: "Iraq", code: 'iq' },
  { name: "Ahmed Qasem", country: "Iraq", code: 'iq' },
  { name: "Zidane Iqbal", country: "Iraq", code: 'iq' },
  { name: "Zaid Ismail", country: "Iraq", code: 'iq' },
  { name: "Aymen Hussein", country: "Iraq", code: 'iq' },
  { name: "Ali Al-Hamadi", country: "Iraq", code: 'iq' },
  { name: "Marko Farji", country: "Iraq", code: 'iq' },
  { name: "Ali Jassim El-Aibi", country: "Iraq", code: 'iq' },
  { name: "Mohanad Ali", country: "Iraq", code: 'iq' },
  { name: "Ali Yousif", country: "Iraq", code: 'iq' },

  // ── UZBEKISTAN ──────────────────────────────
  { name: "Dostonbek Xamdamov", country: "Uzbekistan", code: 'uz' },
  { name: "Otabek Shukurov", country: "Uzbekistan", code: 'uz' },
  { name: "Oston Urunov", country: "Uzbekistan", code: 'uz' },
  { name: "Jamshid Iskanderov", country: "Uzbekistan", code: 'uz' },
  { name: "Akmal Mozgovoy", country: "Uzbekistan", code: 'uz' },
  { name: "Abbosbek Fayzullaev", country: "Uzbekistan", code: 'uz' },
  { name: "Azizjon Ganiev", country: "Uzbekistan", code: 'uz' },
  { name: "Odiljon Hamrobekov", country: "Uzbekistan", code: 'uz' },
  { name: "Sherzod Esanov", country: "Uzbekistan", code: 'uz' },
  { name: "Eldor Shomurodov", country: "Uzbekistan", code: 'uz' },
  { name: "Jaloliddin Masharipov", country: "Uzbekistan", code: 'uz' },
  { name: "Igor Sergeev", country: "Uzbekistan", code: 'uz' },
  { name: "Azizbek Amonov", country: "Uzbekistan", code: 'uz' },

  // ── NETHERLANDS ─────────────────────────────
  { name: "Marten de Roon", country: "Netherlands", code: 'nl' },
  { name: "Donyell Malen", country: "Netherlands", code: 'nl' },
  { name: "Frenkie de Jong", country: "Netherlands", code: 'nl' },
  { name: "Noa Lang", country: "Netherlands", code: 'nl' },
  { name: "Guus Til", country: "Netherlands", code: 'nl' },
  { name: "Teun Koopmeiners", country: "Netherlands", code: 'nl' },
  { name: "Tijjani Reijnders", country: "Netherlands", code: 'nl' },
  { name: "Ryan Gravenberch", country: "Netherlands", code: 'nl' },
  { name: "Mats Wieffer", country: "Netherlands", code: 'nl' },
  { name: "Quinten Timber", country: "Netherlands", code: 'nl' },
  { name: "Crysencio Summerville", country: "Netherlands", code: 'nl' },
  { name: "Cody Gakpo", country: "Netherlands", code: 'nl' },
  { name: "Justin Kluivert", country: "Netherlands", code: 'nl' },
  { name: "Wout Weghorst", country: "Netherlands", code: 'nl' },
  { name: "Memphis Depay", country: "Netherlands", code: 'nl' },
  { name: "Brian Brobbey", country: "Netherlands", code: 'nl' },

  // ── NORWAY ──────────────────────────────────
  { name: "Morten Thorsby", country: "Norway", code: 'no' },
  { name: "Martin Ødegaard", country: "Norway", code: 'no' },
  { name: "Sander Berge", country: "Norway", code: 'no' },
  { name: "Patrick Berg", country: "Norway", code: 'no' },
  { name: "Fredrik Aursnes", country: "Norway", code: 'no' },
  { name: "Kristian Thorstvedt", country: "Norway", code: 'no' },
  { name: "Thelo Aasgaard", country: "Norway", code: 'no' },
  { name: "Antonio Nusa", country: "Norway", code: 'no' },
  { name: "Oscar Bobb", country: "Norway", code: 'no' },
  { name: "Alexander Sørloth", country: "Norway", code: 'no' },
  { name: "Jens Hauge", country: "Norway", code: 'no' },
  { name: "Erling Haaland", country: "Norway", code: 'no' },
  { name: "Andreas Schjelderup", country: "Norway", code: 'no' },
  { name: "Jørgen Strand Larsen", country: "Norway", code: 'no' },

  // ── SCOTLAND ────────────────────────────────
  { name: "Scott McTominay", country: "Scotland", code: 'gb-sct' },
  { name: "Kenny McLean", country: "Scotland", code: 'gb-sct' },
  { name: "Ryan Christie", country: "Scotland", code: 'gb-sct' },
  { name: "Lewis Ferguson", country: "Scotland", code: 'gb-sct' },
  { name: "John McGinn", country: "Scotland", code: 'gb-sct' },
  { name: "Ben Doak", country: "Scotland", code: 'gb-sct' },
  { name: "Findlay Curtis", country: "Scotland", code: 'gb-sct' },
  { name: "Tyler Fletcher", country: "Scotland", code: 'gb-sct' },
  { name: "Che Adams", country: "Scotland", code: 'gb-sct' },
  { name: "George Hirst", country: "Scotland", code: 'gb-sct' },
  { name: "Ross Stewart", country: "Scotland", code: 'gb-sct' },
  { name: "Lyndon Dykes", country: "Scotland", code: 'gb-sct' },
  { name: "Lawrence Shankland", country: "Scotland", code: 'gb-sct' },

  // ── CURAÇAO ─────────────────────────────────
  { name: "Leandro Bacuna", country: "Curaçao", code: 'cuw' },
  { name: "Godfried Roemeratoe", country: "Curaçao", code: 'cuw' },
  { name: "Juninho Bacuna", country: "Curaçao", code: 'cuw' },
  { name: "Kevin Felida", country: "Curaçao", code: 'cuw' },
  { name: "Gervane Kastaneer", country: "Curaçao", code: 'cuw' },
  { name: "Kenji Gorré", country: "Curaçao", code: 'cuw' },
  { name: "Jürgen Locadia", country: "Curaçao", code: 'cuw' },
  { name: "Tahith Chong", country: "Curaçao", code: 'cuw' },
  { name: "Sontje Hansen", country: "Curaçao", code: 'cuw' },
  { name: "Jearl Margaritha", country: "Curaçao", code: 'cuw' },
  { name: "Jeremy Antonisse", country: "Curaçao", code: 'cuw' },
  { name: "Brandley Kuwas", country: "Curaçao", code: 'cuw' },
]
