const PY_TZ = 'America/Asuncion'

const MONTHS_ES = ['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre']
const MONTHS_SH = ['ene','feb','mar','abr','may','jun','jul','ago','sep','oct','nov','dic']

function pyParts(d: Date, opts: Intl.DateTimeFormatOptions): Record<string, string> {
  return Object.fromEntries(
    new Intl.DateTimeFormat('en-CA', { timeZone: PY_TZ, ...opts }).formatToParts(d).map(p => [p.type, p.value])
  )
}

// ─── Date/time formatters — America/Asuncion IANA tz, correct on server + client ─

/** "YYYY-MM-DD" in Paraguay timezone */
export function pyISODate(d: Date): string {
  const { year, month, day } = pyParts(d, { year: 'numeric', month: '2-digit', day: '2-digit' })
  return `${year}-${month}-${day}`
}

/** "HH:mm" in Paraguay timezone */
export function pyTime(d: Date): string {
  const { hour, minute } = pyParts(d, { hour: '2-digit', minute: '2-digit', hourCycle: 'h23' })
  return `${hour}:${minute}`
}

/** "11 jun · 16:00" in Paraguay timezone */
export function pyDateTimeMed(d: Date): string {
  const { day, month } = pyParts(d, { day: 'numeric', month: 'numeric' })
  return `${day} ${MONTHS_SH[Number(month) - 1]} · ${pyTime(d)}`
}

/**
 * "Jueves, 11 de junio" from an ISO date key "2026-06-11".
 * Parses at T12:00:00Z so the offset never shifts the calendar date.
 */
export function pyDateLabel(isoDate: string): string {
  const d = new Date(isoDate + 'T12:00:00Z')
  const { day, month } = pyParts(d, { day: 'numeric', month: 'numeric' })
  const weekday = new Intl.DateTimeFormat('es', { timeZone: PY_TZ, weekday: 'long' }).format(d)
  const cap = weekday.charAt(0).toUpperCase() + weekday.slice(1)
  return `${cap}, ${day} de ${MONTHS_ES[Number(month) - 1]}`
}

// ─── Team name translations (English API → Spanish display) ──────────────────

const TEAM_NAMES_ES: Record<string, string> = {
  'South Korea':              'Corea del Sur',
  'Korea Republic':           'Corea del Sur',
  'Korea DPR':                'Corea del Norte',
  'Czechia':                  'República Checa',
  'Czech Republic':           'República Checa',
  'Bosnia-Herzegovina':       'Bosnia y Herzegovina',
  'Bosnia and Herzegovina':   'Bosnia y Herzegovina',
  'United States':            'Estados Unidos',
  'USA':                      'EE.UU.',
  'Saudi Arabia':             'Arabia Saudita',
  'Ivory Coast':              'C. de Marfil',
  "Cote d'Ivoire":            'C. de Marfil',
  'South Africa':             'Sudáfrica',
  'New Zealand':              'Nueva Zelanda',
  'Iran':                     'Irán',
  'Japan':                    'Japón',
  'France':                   'Francia',
  'Germany':                  'Alemania',
  'Spain':                    'España',
  'England':                  'Inglaterra',
  'Netherlands':              'Países Bajos',
  'Belgium':                  'Bélgica',
  'Switzerland':              'Suiza',
  'Croatia':                  'Croacia',
  'Denmark':                  'Dinamarca',
  'Poland':                   'Polonia',
  'Norway':                   'Noruega',
  'Sweden':                   'Suecia',
  'Ukraine':                  'Ucrania',
  'Wales':                    'Gales',
  'Scotland':                 'Escocia',
  'Serbia':                   'Serbia',
  'Austria':                  'Austria',
  'Australia':                'Australia',
  'Canada':                   'Canadá',
  'Mexico':                   'México',
  'Morocco':                  'Marruecos',
  'Senegal':                  'Senegal',
  'Ghana':                    'Ghana',
  'Nigeria':                  'Nigeria',
  'Egypt':                    'Egipto',
  'Tunisia':                  'Túnez',
  'Algeria':                  'Argelia',
  'Cameroon':                 'Camerún',
  'Ecuador':                  'Ecuador',
  'Colombia':                 'Colombia',
  'Uruguay':                  'Uruguay',
  'Paraguay':                 'Paraguay',
  'Venezuela':                'Venezuela',
  'Honduras':                 'Honduras',
  'Qatar':                    'Catar',
  'Jordan':                   'Jordania',
  'Uzbekistan':               'Uzbekistán',
  'Vietnam':                  'Vietnam',
  'Cape Verde':               'Cabo Verde',
  'Cape Verde Islands':       'Cabo Verde',
  'Curacao':                  'Curaçao',
  'Curaçao':                  'Curaçao',
  'Congo DR':                 'RD del Congo',
  'DR Congo':                 'RD del Congo',
  'Haiti':                    'Haití',
  'Iraq':                     'Irak',
  'Argentina':                'Argentina',
  'Brazil':                   'Brasil',
  'Chile':                    'Chile',
  'Peru':                     'Perú',
  'Bolivia':                  'Bolivia',
  'Italy':                    'Italia',
  'Greece':                   'Grecia',
  'Turkey':                   'Turquía',
  'Russia':                   'Rusia',
  'Romania':                  'Rumania',
  'Hungary':                  'Hungría',
  'Slovenia':                 'Eslovenia',
  'Slovakia':                 'Eslovaquia',
  'Costa Rica':               'Costa Rica',
  'Panama':                   'Panamá',
  'Jamaica':                  'Jamaica',
  'Trinidad and Tobago':      'Trinidad y Tobago',

  // ── Champions League clubs ────────────────────────────────────────────────
  'FC Bayern München':               'Bayern Múnich',
  'FC Bayern Munich':                'Bayern Múnich',
  'Bayern München':                  'Bayern Múnich',
  'Bayern Munich':                   'Bayern Múnich',
  'Real Madrid CF':                  'Real Madrid',
  'FC Barcelona':                    'Barcelona',
  'Club Atlético de Madrid':         'Atlético Madrid',
  'Atlético de Madrid':              'Atlético Madrid',
  'Atletico de Madrid':              'Atlético Madrid',
  'Paris Saint-Germain FC':          'PSG',
  'Paris Saint-Germain':             'PSG',
  'Manchester City FC':              'Manchester City',
  'Liverpool FC':                    'Liverpool',
  'Arsenal FC':                      'Arsenal',
  'Chelsea FC':                      'Chelsea',
  'Tottenham Hotspur FC':            'Tottenham',
  'Manchester United FC':            'Manchester United',
  'Juventus FC':                     'Juventus',
  'AC Milan':                        'Milan',
  'FC Internazionale Milano':        'Internazionale',
  'Inter Milan':                     'Internazionale',
  'SS Lazio':                        'Lazio',
  'AS Roma':                         'Roma',
  'SSC Napoli':                      'Napoli',
  'Atalanta BC':                     'Atalanta',
  'Borussia Dortmund':               'Dortmund',
  'Bayer 04 Leverkusen':             'Leverkusen',
  'RB Leipzig':                      'Leipzig',
  'Eintracht Frankfurt':             'Eintracht Frankfurt',
  'VfL Wolfsburg':                   'Wolfsburg',
  'FC Porto':                        'Porto',
  'SL Benfica':                      'Benfica',
  'Sporting CP':                     'Sporting CP',
  'AFC Ajax':                        'Ajax',
  'PSV Eindhoven':                   'PSV',
  'Feyenoord':                       'Feyenoord',
  'Celtic FC':                       'Celtic',
  'Rangers FC':                      'Rangers',
  'Sevilla FC':                      'Sevilla',
  'Real Sociedad de Fútbol':         'Real Sociedad',
  'Real Betis Balompié':             'Betis',
  'Villarreal CF':                   'Villarreal',
  'RC Lens':                         'Lens',
  'Olympique de Marseille':          'Marseille',
  'Olympique Lyonnais':              'Lyon',
  'Stade de Reims':                  'Reims',
  'Girona FC':                       'Girona',
  'Club Brugge KV':                  'Brujas',
  'RSC Anderlecht':                  'Anderlecht',
  'BSC Young Boys':                  'Young Boys',
  'FC Basel 1893':                   'Basel',
  'FC Red Bull Salzburg':            'Salzburg',
  'Red Bull Salzburg':               'Salzburg',
  'SK Sturm Graz':                   'Sturm Graz',
  'Shakhtar Donetsk':                'Shakhtar',
  'Dynamo Kyiv':                     'Dynamo Kiev',
  'GNK Dinamo Zagreb':               'Dinamo Zagreb',
  'HNK Hajduk Split':                'Hajduk Split',
  'FK Crvena zvezda':                'Estrella Roja',
  'Red Star Belgrade':               'Estrella Roja',
  'Crvena zvezda':                   'Estrella Roja',
  'FK Partizan':                     'Partizán',
  'FK Shakhtar Donetsk':             'Shakhtar',
  'Fenerbahçe SK':                   'Fenerbahçe',
  'Galatasaray AŞ':                  'Galatasaray',
  'Beşiktaş JK':                     'Beşiktaş',
  'Trabzonspor AŞ':                  'Trabzonspor',
  'VfB Stuttgart':                   'Stuttgart',
  'Sport-Club Freiburg':             'Friburgo',
  'FC Augsburg':                     'Augsburgo',
  'Hamburger SV':                    'Hamburgo',
  'Werder Bremen':                   'Werder Bremen',
  'FC Schalke 04':                   'Schalke',
  'Borussia Mönchengladbach':        'Mönchengladbach',
  '1. FC Union Berlin':              'Union Berlín',
  'Hertha BSC':                      'Hertha',
  '1. FC Köln':                      'Colonia',
  'Brentford FC':                    'Brentford',
  'Aston Villa FC':                  'Aston Villa',
  'Newcastle United FC':             'Newcastle',
  'West Ham United FC':              'West Ham',
  'Wolverhampton Wanderers FC':      'Wolves',
  'Brighton & Hove Albion FC':       'Brighton',
  'Fulham FC':                       'Fulham',
  'Leicester City FC':               'Leicester',
  'Everton FC':                      'Everton',
  'Crystal Palace FC':               'Crystal Palace',
  'Nottingham Forest FC':            'Nottingham Forest',
  'Monaco FC':                       'Mónaco',
  'AS Monaco FC':                    'Mónaco',
  'Stade Rennais FC 1901':           'Rennes',
  'LOSC Lille':                      'Lille',
  'Lille OSC':                       'Lille',
  'RC Strasbourg Alsace':            'Estrasburgo',
  'Montpellier HSC':                 'Montpellier',
  'OGC Nice':                        'Niza',
  'Nantes FC':                       'Nantes',
  'FC Nantes':                       'Nantes',
  'Toulouse FC':                     'Toulouse',
  'Stade Brestois 29':               'Brest',
  'AZ Alkmaar':                      'AZ Alkmaar',
  'FK Atlético Madrid':              'Atlético Madrid',
  'Sporting Clube de Portugal':      'Sporting CP',
  'SC Braga':                        'Braga',
  'Vitória SC':                      'Vitória',
  'FK Crvena Zvezda':                'Estrella Roja',
  'FC Viktoria Plzeň':               'Viktoria Plzeň',
  'AC Sparta Praha':                 'Sparta Praga',
  'SK Slavia Praha':                 'Slavia Praga',
  'Sparta Prague':                   'Sparta Praga',
  'Slavia Prague':                   'Slavia Praga',
  'Legia Warszawa':                  'Legia Varsovia',
  'KRC Genk':                        'Genk',
  'Royale Union Saint-Gilloise':     'Union SG',
  'FK Bodø/Glimt':                   'Bodø/Glimt',
  'FC Midtjylland':                  'Midtjylland',
  'Brøndby IF':                      'Brøndby',
  'FC Copenhagen':                   'Copenhague',
  'Malmö FF':                        'Malmö',
  'IF Elfsborg':                     'Elfsborg',
  'PAOK FC':                         'PAOK',
  'Olympiacos CFP':                  'Olympiacos',
  'AEK Athens FC':                   'AEK Atenas',
  'Panathinaikos FC':                'Panathinaikos',
  'FK BATE Borisov':                 'BATE Borisov',
  'HB Køge':                         'HB Køge',
  'Ferencvárosi TC':                 'Ferencváros',
  'Ferencváros':                     'Ferencváros',
  'FK Qarabağ':                      'Qarabağ',
  'Qarabağ FK':                      'Qarabağ',
  'FC Astana':                       'Astana',
  'CFR 1907 Cluj':                   'CFR Cluj',
  'FK Maccabi Tel Aviv':             'Maccabi Tel Aviv',
  'Maccabi Tel Aviv FC':             'Maccabi Tel Aviv',
  'Maccabi Haifa FC':                'Maccabi Haifa',
  'Hapoel Beer Sheva FC':            'Hapoel Beer Sheva',
  'FC Sheriff':                      'Sheriff Tiraspol',
  'Sheriff Tiraspol':                'Sheriff Tiraspol',
  'FK Rosenborg BK':                 'Rosenborg',
  'FC Slovan Bratislava':            'Slovan Bratislava',
  'Servette FC':                     'Servette',
  'FC Luzern':                       'Lucerna',
  'Ludogorets Razgrad':              'Ludogorets',
  'PFC Ludogorets 1945':             'Ludogorets',
  'FK RFS':                          'RFS',
  'FK Riga':                         'FK Riga',
  'FC Differdange 03':               'Differdange',
  'Lincoln Red Imps FC':             'Lincoln Red Imps',
  'Hamrun Spartans FC':              'Hamrun Spartans',
  'The New Saints FC':               'The New Saints',
  'Shamrock Rovers FC':              'Shamrock Rovers',
  'Bohemian FC':                     'Bohemian',
  'Derry City FC':                   'Derry City',
  'Aris Limassol FC':                'Aris Limassol',
  'APOEL FC':                        'APOEL',
  'AEK Larnaca FC':                  'AEK Larnaca',
  'Pafos FC':                        'Pafos',
  'HJK Helsinki':                    'HJK Helsinki',
  'IF Brommapojkarna':               'Brommapojkarna',
  'RC Celta de Vigo':                'Celta',
  'Valencia CF':                     'Valencia',
  'Rayo Vallecano de Madrid':        'Rayo Vallecano',
  'Deportivo Alavés':                'Alavés',
  'Cádiz CF':                        'Cádiz',
  'UD Las Palmas':                   'Las Palmas',
  'FC Girona':                       'Girona',
  'AS Saint-Étienne':                'Saint-Étienne',
  'Sporting Clube de Braga':         'Braga',
  'FC Union Berlin':                 'Union Berlín',
  'TSG 1899 Hoffenheim':             'Hoffenheim',
  '1. FSV Mainz 05':                 'Mainz',
  'SV Werder Bremen':                'Werder Bremen',
  'Hannover 96':                     'Hannover',
  'Celtic Football Club':            'Celtic',
  'Club Brugge':                     'Brujas',
  'Aston Villa':                     'Aston Villa',
  'Newcastle United':                'Newcastle',
  'West Ham United':                 'West Ham',
  'Brentford':                       'Brentford',
  'Brighton':                        'Brighton',
}

export function getTeamNameES(name: string | null | undefined): string {
  if (!name) return ''
  return TEAM_NAMES_ES[name] ?? name
}
